In [1]:
import numpy as np

Creating 1 dimensional array

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

printing the arr1 and arr2

In [4]:
print("Array 1:", arr1)
print("Array 2:", arr2)
print(arr1.shape)

Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]
(5,)


combining two array into arr3

In [5]:
arr3 = np.concatenate((arr1, arr2))
print("Concatenated Array:", arr3)

Concatenated Array: [ 1  2  3  4  5  6  7  8  9 10]


Array concatenation with
1. horizontal stack
2. vertical stack
3. column stack
4. axis = 1 , row
5. axis = 0, col

In [15]:
arr4 = np.hstack((arr1,arr2))
print("Horizontally Stacked Array:", arr4)
arr5 = np.vstack((arr1, arr2))
print("Vertically Stacked Array:\n", arr5)
print("Shape of Stacked Array:", arr5.shape)
arr6 = np.column_stack((arr1, arr2))    
print("Column Stacked Array:\n", arr6)
arr7 = np.stack((arr1, arr2), axis=1)
print("Stacked Array with axis=1:\n", arr7)
arr8 = np.stack((arr1, arr2), axis=0)
print("Stacked Array with axis=0:\n", arr8)

Horizontally Stacked Array: [ 1  2  3  4  5  6  7  8  9 10]
Vertically Stacked Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape of Stacked Array: (2, 5)
Column Stacked Array:
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
Stacked Array with axis=1:
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
Stacked Array with axis=0:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Reshape the array, it is not a inplace operation

In [10]:
print(arr3.reshape(5,2))
print("arr3",arr3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
arr3 [ 1  2  3  4  5  6  7  8  9 10]


Some built in array creating methods

In [20]:
ones = np.ones((3, 2))
print("Ones Array:\n", ones)

zeros = np.zeros((3, 2))
print("Zeros Array:\n", zeros)

identity = np.eye(3)
print("Identity Matrix:\n", identity)

diagonal = np.diag([1, 2, 3])
print("Diagonal Matrix:\n", diagonal)

Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Zeros Array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


generate array between a range with step, if step is not given then it takes 1 as default value. end value is exclusive.

In [16]:
range_array = np.arange(10, 20, 2)
print("Range Array:", range_array)

Range Array: [10 12 14 16 18]


generating array between a range but last argument is not step, is how much do you want. end value is inclusive

In [18]:
linspace_array = np.linspace(0, 1, 5)
print("Linspace Array:", linspace_array)

Linspace Array: [0.   0.25 0.5  0.75 1.  ]


Common attributes of an array

In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:\n", arr)
print("Shape of Array:", arr.shape)
print("Data Type of Array:", arr.dtype)
print("Array size:", arr.size)
print("Array Dimension:", arr.ndim)
print("Item size in bytes:", arr.itemsize)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of Array: (3, 3)
Data Type of Array: int64
Array size: 9
Array Dimension: 2
Item size in bytes: 8


In [24]:
print("Minimum Value in Array:", arr.min())
print("Maximum Value in Array:", arr.max())
print("Array Transpose:\n", arr.T)
print("Flattened Array:", arr.flatten())
print("Max value in each column:", arr.max(axis=0))
print("Max value in each row:", arr.max(axis=1))

Minimum Value in Array: 1
Maximum Value in Array: 9
Array Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Flattened Array: [1 2 3 4 5 6 7 8 9]
Max value in each column: [7 8 9]
Max value in each row: [3 6 9]


Vector Operations

In [27]:
print("Array 1:", arr1)
print("Array 2:", arr2)

print("Element-wise Addition:", arr1 + arr2)
print("Element-wise Subtraction:", arr1 - arr2)
print("Element-wise Multiplication:", arr1 * arr2)
print("Element-wise Division:", arr1 / arr2)
print("Element-wise Modulus:", arr1 % arr2)

Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]
Element-wise Addition: [ 7  9 11 13 15]
Element-wise Subtraction: [-5 -5 -5 -5 -5]
Element-wise Multiplication: [ 6 14 24 36 50]
Element-wise Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Element-wise Modulus: [1 2 3 4 5]


Common math
1. square root
2. exponent
3. sin
4. log
Operations are not inplace. so if you need the change then use another variable.

In [29]:
print("Array 1:", arr1)
print("square root of Array 1:", np.sqrt(arr1))
print("Array 1:", arr1)
print("Exponential of Array 1:", np.exp(arr1))
print("sin of Array 1:", np.sin(arr1))
print("cos of Array 1:", np.cos(arr1))
print("tan of Array 1:", np.tan(arr1))
print("log of Array 1:", np.log(arr1))
print("log10 of Array 1:", np.log10(arr1))

Array 1: [1 2 3 4 5]
square root of Array 1: [1.         1.41421356 1.73205081 2.         2.23606798]
Array 1: [1 2 3 4 5]
Exponential of Array 1: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
sin of Array 1: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
cos of Array 1: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
tan of Array 1: [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
log of Array 1: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
log10 of Array 1: [0.         0.30103    0.47712125 0.60205999 0.69897   ]


Array slicing is similar to python, for row and col you can use two brackets like, arr[row][col] or you can use single bracket with comma arr[row, col]

In [30]:
tow_dimensional_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Two Dimensional Array:\n", tow_dimensional_array)
print("Shape of Two Dimensional Array:", tow_dimensional_array.shape)
print("Data Type of Two Dimensional Array:", tow_dimensional_array.dtype)
print(arr[1, 2])  # Accessing element at row 1, column 2
print("Row 1 of Two Dimensional Array:", tow_dimensional_array[1])  # Accessing row 1
print("Column 2 of Two Dimensional Array:", tow_dimensional_array[:, 1])  # Accessing column 2

Two Dimensional Array:
 [[1 2 3]
 [4 5 6]]
Shape of Two Dimensional Array: (2, 3)
Data Type of Two Dimensional Array: int64
6
Row 1 of Two Dimensional Array: [4 5 6]
Column 2 of Two Dimensional Array: [2 5]


Statistical operations
1. mean
2. median
3. mode
4. standard deviation
5. variance

In [34]:
print("Mean of Array 1:", np.mean(arr1))
print("Standard Deviation of Array 1:", np.std(arr1))
print("Variance of Array 1:", np.var(arr1))
print("Median of Array 1:", np.median(arr1))
print("Modde of Array 1:", np.argmax(arr1))  # Index of the maximum value
normalizedd_arr1 = (arr1 - np.mean(arr1)) / np.std(arr1)
print("Normalized Array 1:", normalizedd_arr1)

Mean of Array 1: 3.0
Standard Deviation of Array 1: 1.4142135623730951
Variance of Array 1: 2.0
Median of Array 1: 3.0
Modde of Array 1: 4
Normalized Array 1: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


Logical operations.

like other programming languages, dont use && ,instead use & for logical and 

In [38]:
print("Array 1:", arr1)
print("greater than 3 in Array 1:", arr1[arr1 > 3])
print("less than 3 in Array 1:", arr1[arr1 < 3])
print("greater then 2 and less than 5 in Array 1:", arr1[(arr1 > 2) & (arr1 < 5)])

Array 1: [1 2 3 4 5]
greater than 3 in Array 1: [4 5]
less than 3 in Array 1: [1 2]
greater then 2 and less than 5 in Array 1: [3 4]
